blog/urls.py
from django.urls import path
from . import views

app_name='blog'
urlpatterns=[
    path('', views.PostListView.as_view(), name='post_list'),
    path('detail/<int:pk>/',views.PostDetailView.as_view(), name='post_detail'),
    path('create/',views.PostCreateView.as_view(), name='post_create'),
    path('delete/<int:pk>',views.PostDeleteView.as_view(),name='post_delete'),
    path('update/<int:pk>',views.PostUpdateView.as_view(),name='post_update')


]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import homePage
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homePage.as_view(), name='home'),
    path('blog/', include('blog.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    author =models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now())
    published_date = models.DateTimeField(blank = True, null = True)
    image = models.ImageField(upload_to='pics', blank=True,null=True)


    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_Date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment
from django.forms.widgets import HiddenInput

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields = ('title', 'author', 'text','image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'post'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields=('author','text','post')
        widgets = {}
        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'comment'}),
            'post': forms.HiddenInput()
        }
            

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.views.generic.edit import FormMixin
from django.contrib import messages


# Create your views here.
from django.http import HttpResponse

from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy

class homePage(TemplateView):
    template_name='blog/home.html'

class PostListView(ListView):
    context_object_name='post_list'
    model =Post
    def get_queryset(self):
        return Post.objects.filter().order_by('-created_date')

class PostDetailView(FormMixin,DetailView):
    context_object_name= 'post_detail'
    model=Post
    form_class=CommentForm
    def get_success_url(self):
        return reverse('blog:post_detail',kwargs={'pk':self.object.id})
    
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm(initial={'post': self.object})
        return context

    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            print('form_valid')
            return self.form_valid(form)
        else:
            print('form invalid')
            print(messages.error)
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(PostDetailView, self).form_valid(form)
    

class PostCreateView(CreateView):
    form_class=PostForm
    model = Post


class PostUpdateView(UpdateView):
    fields=('title', 'author', 'text')
    model = Post

class PostDeleteView(DeleteView):
    model = Post
    success_url=reverse_lazy('blog:post_list')
    template_name='blog/post_delete.html'

templates/blog/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{%url 'blog:post_list'%}">My Blog</a>
       
        
           
              <a class="navbar-brand" href="{%url 'blog:post_create'%}">Create</a>
            
          
        
        </div>
      </nav>
            
    {%block content%} 
    {%endblock%}   
</body>
</html>

templates/blog/home.html
{%extends 'blog/base.html'%}

{%block content%}
<h1>
    welcome to app homepage
</h1>
{%endblock%}

templates/blog/post_delete.html
{%extends 'blog/base.html'%}

{%block content%}

<h3>are you sure you want to delete {{post.title}}</h3>

<form method="Post">
    {%csrf_token%}
    <input type="submit" value="Confirm" class='btn btn-danger'>
    <a href="{%url 'blog:post_detail' pk=post.pk%}" class='btn btn-primary'>Cancel</a>
</form>


{%endblock%}

templates/blog/post_detail.html
{%extends 'blog/base.html'%}
{%block content%}
<div class="container">
    <div class="jumbotron">

<h1>
    <center> {{post_detail.title}}</center>
</h1>

<p>
    <center>
    {%if post_detail.image%}
    <img src="{{ post_detail.image.url }}">
    {%else%}
    no image associated
    {%endif%}
</center>
</p>

<p>{{post_detail.text}}</p>

<a href="{%url 'blog:post_delete' pk=post_detail.pk%}" class='btn btn-danger'>Delete</a>
<a href="{%url 'blog:post_update' pk=post_detail.pk%}"class='btn btn-primary'>Edit</a>
<hr>
{%for comment in post_detail.comments.all%}
{%if comment.approved_comment%}
<div class="container">
    <div class="row">
      <div class="col-12">
        <div class="comments">
          <div class="comment-box">
            <span class="commenter-pic">
              <img src="" class="img-fluid">
            </span>
            <span class="commenter-name">
              <a href="#">{{comment.author}}</a> <span class="comment-time">{{comment.created_Date|date:"d M, Y" }}</span>
            </span>       
            <p class="comment-txt more">
                {{comment.text}}
            </p>
            
              </div>
            </div>
          </div>
        </div>
      </div>

      <hr>



<hr>

{%endif%}
{%empty%}
<p>no comments to show</p>
{%endfor%}

<h4>Add a comment</h4>
<form action="" method="POST">
    {%csrf_token%}
    {{form.author.label}}: {{form.author}}
    <p>
    {{form.text.label}}: {{form.text}}
    <p>
       {{form.post}}
    </p>
</p>
<input type="submit" value="Comment">
</form>

</div>

</div>



  
  
  <script>
      // Reply box popup JS
      $(document).ready(function(){
        $(".reply-popup").click(function(){
          $(".reply-box").toggle();
        });
      });
      </script>


{%endblock%}

templates/blog/post_form.html
{%extends 'blog/base.html'%}

{%block content%}
<div class="container" >
    <form method='Post' enctype="multipart/form-data">
        {%csrf_token%}
    {{form.as_p}}

    <input type="submit" value="Publish">
</form>
    </div>
{%endblock%}

templates/blog/post_list.html
{%extends 'blog/base.html'%}
{%block content%}
<div class="container">
  <div class="jumbotron">
  
<h1>
  <center>
  Posted Blog!!!
</center>
</h1>


<div class="row">
    {%for post in post_list%}
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{post.title|capfirst}}</h5>
          <p class="card-text">{{post.text|slice:'100'}}</p>
          <a href="{%url 'blog:post_detail' pk=post.pk%}" class="btn btn-primary">Read More</a>
          <div class="card-footer text-muted">
            {{post.created_date|date:"d M, Y"}}
          </div>
        </div>
      </div>
    </div>
    
    {%endfor%}  
 </div>
{%endblock%}

</div>  
</div>